### ISSUE TITLE
STM32F103C8T6 Serial dump does not stop

### ISSUE THREAD

**Issue by MoeBenMtl** [CTXz/stm32f1-picopwner#20]
Hello I would like to thank you for sharing this utility and also ask a question about an issue I am having I have an STM32F103C8T6 Rev X 
the process works fine but when I get to the serial dumping part it keeps dumping data forever ... if anyone has an idea please let me know

**Comment by MoeBenMtl** [comment]
I had the same reflection, I left it dumping until it reached 2048kb file size which made no sense.

**Comment by CTXz** [comment]
I can't say for sure until I've tested, but perhaps it enters a loop where it resets after receiving the hardfault, which in return jumps back to the start of stage 1.

Try the following traget binaries and let me know if they fix the issue:

[target_firmware_v1.3.1tar.gz](https://github.com/CTXz/stm32f1-picopwner/files/14465007/target_firmware_v1.3.1tar.gz)

If this still doesn't do it, I'll take a closer look at this tommorow.

**Comment by MoeBenMtl** [comment]
Same outcome loops forever past 128kb also does seem to be in some sort of loop as the data that's being printed looks repetitive

**Comment by CTXz** [comment]
Alright, I'd just like to confirm that this is related to the latest release. Would you mind trying the last release?

https://github.com/CTXz/stm32f1-picopwner/releases/tag/a1.2_t1.2

Make sure to use the dump script from that release as well.

**Comment by MoeBenMtl** [comment]
Yes sure NP

**Comment by MoeBenMtl** [comment]
I wiped and used last release and I have the same exact issue.

**Comment by MoeBenMtl** [comment]
![image](https://github.com/CTXz/stm32f1-picopwner/assets/96128424/c47668ff-ed7b-4242-a0cb-00c0c99bef66)

here the dump

**Comment by CTXz** [comment]
Huh, that's rather interesting. It appears that this issue is unique to your set-up then.

I'll see if I can implement a condition in the dump.py script tommorow that rejects incoming data after the connected device's flash size has been dumped. Or at the very least, I'll add a flag that can restrict the dump file size to a provided size. That way, even if such an endless loop occurs, the script will still complete the dump.

**Comment by MoeBenMtl** [comment]
Alright, Ty also doesn't the data looks like it's dumping the same thing over and over ?

**Comment by CTXz** [comment]
Wups, I didn't pay enough attention to the image. I had assumed it's looping at the stop of the flash. You're right, in this case the proposed solution obviously won't be very useful. It seems to be looping after transmitting 404 bytes. It's also clearly resetting, as the start magic `0x10ADDA7A` is being transmitted at the start of every repeat. Something must be triggering a reset.

I'll upload a couple of test firmware binaries later that could further diagnose what's potentially causing the issue. If you have an oscilloscope, perhaps you could monitor the reset line and see if it experiences some sort of voltage flunctiuations that could cause the reset to trigger. If that's not an option, a multimeter reading of the NRST pin could also potentially help. That being said, the reset being triggered at exactly 404 bytes makes a hardware related issue less likely.

**Comment by MoeBenMtl** [comment]
You are right RST keeps getting triggered on original pcb nrst is tied to 3.3v
![IMG_3176](https://github.com/CTXz/stm32f1-picopwner/assets/96128424/6871a7b0-9cdf-405d-b3e9-cd8037bcc0be)

**Comment by CTXz** [comment]
Ok, I've come up with a workaround that should be able to dump despite experiencing resets.

Please use the following attack and target fimrwares and let me know how things look this time:

[target_firmware_v1.3_rst_Workaround.tar.gz](https://github.com/CTXz/stm32f1-picopwner/files/14471463/target_firmware_v1.3_rst_Workaround.tar.gz)
[attack.zip](https://github.com/CTXz/stm32f1-picopwner/files/14471465/attack.zip)

The latest dump.py should be used

**Comment by MoeBenMtl** [comment]
Amazing ! Ty will try in a bit and report

**Comment by MoeBenMtl** [comment]
Omg ! This worked mint ! Thank you !

**Comment by CTXz** [comment]
Sweet! In this case I'll close the issue now.

Cheers!

**Comment by deividAlfa** [comment]
Regarding this:
I recently discovered clones/fakes report no flash size  (Flash size register=0xFFFFFFFF).
This will cause up to 64MB to be dumped, but shouldn't be a concern because accessing unimplemented memory should cause hard fault and inmediately stop the transfer.
