### ISSUE TITLE
0x618

### ISSUE THREAD

**Issue by 0xbbbbbbbb** [CTXz/stm32f1-picopwner#4]
STM32F1 target is confirmed to be read protected
Detected SRAM entry point offset: 0x618 (0x20000618)
SRAM entry point offset 0x618 is not supported, expected: 0x108, 0x1CC or 0x1E
If you believe this is a valid entry point, please submit an issue

**Comment by 0xbbbbbbbb** [comment]
before upload  target_1e0_usart1.bin
after read SRAM entry point offset is : 0x618 (0x20000618)

**Comment by CTXz** [comment]
Interesting, what type of STM32F1 exactly are you using?

**Comment by CTXz** [comment]
Since this issue has been inactive for longer than a month now, I will close it.
I will gladly re-open it if necessary.
